apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-replicator
  labels:
    app: pvc-replicator
    app.kubernetes.io/component: pvc-replicator
    app.kubernetes.io/instance: pvc-replicator
    app.kubernetes.io/name: pvc-replicator
    app.kubernetes.io/part-of: pvc-replicator-app
  annotations:
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/Fuangwith-Bkk/pvc-replicator'
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-replicator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: pvc-replicator
        deployment: pvc-replicator
    spec:
      # --- IMPORTANT: If your external registry is private, add imagePullSecrets here ---
      # imagePullSecrets:
      #   - name: my-private-registry-secret # Replace with the actual name of your secret
      volumes:
        - name: my-rwx
          persistentVolumeClaim:
            claimName: my-rwx # Ensure this PVC exists and is 'Filesystem' mode
        - name: my-rwo
          persistentVolumeClaim:
            claimName: my-rwo # Ensure this PVC exists
      containers:
        - name: pvc-replicator
          # --- CHANGED: Use your external registry path and tag ---
          image: 'your-external-registry.com/your-org/pvc-replicator:latest' # <<< Replace with your actual image path
          # Example: 'quay.io/myorg/pvc-replicator:v1.0'
          # Example: 'docker.io/myusername/pvc-replicator:latest'
          env:
            - name: SOURCE_PVC_PATH
              value: /mnt/source
            - name: DESTINATION_PVC_PATH
              value: /mnt/dest
            - name: INTERVAL_SECONDS
              value: '5'
          resources: {} # Define your CPU/memory requests/limits here for production
          volumeMounts:
            - name: my-rwo
              mountPath: /mnt/dest
            - name: my-rwx
              mountPath: /mnt/source # This will correctly mount your RWX filesystem PVC
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {} # Add securityContext if needed for specific permissions
      schedulerName: default-scheduler